# Generated by Django 3.2.5 on 2021-07-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('Eng', 'English'), ('Tel', 'Telugu'), ('Hin', 'Hindi')], default='Eng', help_text="Book's language", max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(help_text='Language in which this book is written', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
